### ISSUE TITLE
Castellated holes, workaround

### ISSUE THREAD

**Issue by zigastegu** [carrotIndustries/pluto#11]
Thank you for sharing you design files!
Files were not accepted by "my" PCB Fab so I sent them gerbers where EdgeCuts has some small ears.
Will share if and how goes through
![image](https://user-images.githubusercontent.com/1379063/34225273-16c06ede-e5c6-11e7-87b3-5c09ae1807c8.png)

**Comment by zigastegu** [comment]
It went through fine. Cutting 0.6mm material is easy
Don't know how long HASL contacts for buttons will last? ENIG would probably be better

![pcb](https://user-images.githubusercontent.com/1379063/34436059-86c69992-ec92-11e7-841b-cbbe0aec95c0.jpg)

**Comment by zigastegu** [comment]
@carrotIndustries 
Should I create a pull request for different branch or on the master branch?
It seems this option is cheaper compared to castellated holes although overall size did increase slightly

**Comment by carrotIndustries** [comment]
Great hack to work around silly PCB fabs! A different branch would be the best place for this.

**Comment by zigastegu** [comment]
https://github.com/luftek/pluto/commit/705c0e43f033279aaf257b78690a6cdfd135f872
Currently I am able to post a pull request only to master branch.
Please create second branch in your repo
