### ISSUE TITLE
(off topic) NRF51/52

### ISSUE THREAD

**Issue by Paffo** [carrotIndustries/pluto#15]
Hello,
It's not an issue but rather I'm humbly asking for your expertise. 

I'd be interested to do the same kind of classic watch conversion, but I require BLE support so I was wondering if an NRF51822 or similar, with it's relative passive components, would fit in the same enclose like yours.

My objective, feature wise, is for it to still be a simple clock, but with BLE support for advertising and maybe although optionally, generate OTP codes.

What do you think?

Thank you in advance

**Comment by carrotIndustries** [comment]
> NRF51822

Has no LCD controller.

If I was to make a new iteration of this project that supports BLE, I'd probably go with an STM32WB55. They have BLE and an LCD controller.
